name: Scrape, build, and deploy

on:
  # Runs on pushes targeting the default branch
  #push:
  branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs on a schedule, every five minutes. ArcGIS server publishes every five minutes. 
  schedule:
    - cron:  '*/5 * * * *'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  main:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps: 
    - name: Check out the repo
      id: repocheckout
      uses: actions/checkout@v5
    - name: Fetch data and build page
      id: buildpage
      run: |-
        bash ./main.sh
    - name: Setup Pages
      id: setuppage
      uses: actions/configure-pages@v5
    - name: Upload artifact
      id: uploadpage
      uses: actions/upload-pages-artifact@v3
      with:
        path: web/
    - name: Deploy to GitHub Pages
      id: deploypage
      uses: actions/deploy-pages@v4
